package demo.bankaccount;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Nome")
   private java.lang.String nome;
   @org.kie.api.definition.type.Label("Sobrenome")
   private java.lang.String sobrenome;
   @org.kie.api.definition.type.Label("RG")
   private java.lang.String rg;
   @org.kie.api.definition.type.Label("Email")
   private java.lang.String email;
   @org.kie.api.definition.type.Label("Telefone")
   private java.lang.String telefone;
   @org.kie.api.definition.type.Label("Renda Mensal")
   private Integer salario;

   @org.kie.api.definition.type.Label(value = "Limite")
   private java.lang.Integer limite;

   public Cliente()
   {
   }

   public java.lang.String getNome()
   {
      return this.nome;
   }

   public void setNome(java.lang.String nome)
   {
      this.nome = nome;
   }

   public java.lang.String getSobrenome()
   {
      return this.sobrenome;
   }

   public void setSobrenome(java.lang.String sobrenome)
   {
      this.sobrenome = sobrenome;
   }

   public java.lang.String getRg()
   {
      return this.rg;
   }

   public void setRg(java.lang.String rg)
   {
      this.rg = rg;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getTelefone()
   {
      return this.telefone;
   }

   public void setTelefone(java.lang.String telefone)
   {
      this.telefone = telefone;
   }

   public java.lang.Integer getSalario()
   {
      return this.salario;
   }

   public void setSalario(java.lang.Integer salario)
   {
      this.salario = salario;
   }

   public java.lang.Integer getLimite()
   {
      return this.limite;
   }

   public void setLimite(java.lang.Integer limite)
   {
      this.limite = limite;
   }

   public Cliente(java.lang.String nome, java.lang.String sobrenome,
         java.lang.String rg, java.lang.String email, java.lang.String telefone,
         java.lang.Integer salario, java.lang.Integer limite)
   {
      this.nome = nome;
      this.sobrenome = sobrenome;
      this.rg = rg;
      this.email = email;
      this.telefone = telefone;
      this.salario = salario;
      this.limite = limite;
   }

}