package demo.bankaccount;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Nome")
   private java.lang.String nome;
   @org.kie.api.definition.type.Label(value = "Sobrenome")
   private java.lang.String sobrenome;
   @org.kie.api.definition.type.Label(value = "RG")
   private java.lang.String rg;
   @org.kie.api.definition.type.Label(value = "Email")
   private java.lang.String email;
   @org.kie.api.definition.type.Label(value = "Telefone")
   private java.lang.String telefone;
   @org.kie.api.definition.type.Label(value = "Renda Mensal")
   private java.lang.String salario;

   public Cliente()
   {
   }

   public java.lang.String getNome()
   {
      return this.nome;
   }

   public void setNome(java.lang.String nome)
   {
      this.nome = nome;
   }

   public java.lang.String getSobrenome()
   {
      return this.sobrenome;
   }

   public void setSobrenome(java.lang.String sobrenome)
   {
      this.sobrenome = sobrenome;
   }

   public java.lang.String getRg()
   {
      return this.rg;
   }

   public void setRg(java.lang.String rg)
   {
      this.rg = rg;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getTelefone()
   {
      return this.telefone;
   }

   public void setTelefone(java.lang.String telefone)
   {
      this.telefone = telefone;
   }

   public java.lang.String getSalario()
   {
      return this.salario;
   }

   public void setSalario(java.lang.String salario)
   {
      this.salario = salario;
   }

   public Cliente(java.lang.String nome, java.lang.String sobrenome,
         java.lang.String rg, java.lang.String email,
         java.lang.String telefone, java.lang.String salario)
   {
      this.nome = nome;
      this.sobrenome = sobrenome;
      this.rg = rg;
      this.email = email;
      this.telefone = telefone;
      this.salario = salario;
   }

}