package demo.bankaccount;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class endereco implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "cep")
   private java.lang.String cep;
   @org.kie.api.definition.type.Label(value = "logradouro")
   private java.lang.String logradouro;
   @org.kie.api.definition.type.Label(value = "complemento")
   private java.lang.String complemento;
   @org.kie.api.definition.type.Label(value = "bairro")
   private java.lang.String bairro;
   @org.kie.api.definition.type.Label(value = "localidade")
   private java.lang.String localidade;
   @org.kie.api.definition.type.Label(value = "uf")
   private java.lang.String uf;
   @org.kie.api.definition.type.Label(value = "unidade")
   private java.lang.String unidade;
   @org.kie.api.definition.type.Label(value = "ibge")
   private java.lang.String ibge;
   @org.kie.api.definition.type.Label(value = "gia")
   private java.lang.String gia;

   public endereco()
   {
   }

   public java.lang.String getCep()
   {
      return this.cep;
   }

   public void setCep(java.lang.String cep)
   {
      this.cep = cep;
   }

   public java.lang.String getLogradouro()
   {
      return this.logradouro;
   }

   public void setLogradouro(java.lang.String logradouro)
   {
      this.logradouro = logradouro;
   }

   public java.lang.String getComplemento()
   {
      return this.complemento;
   }

   public void setComplemento(java.lang.String complemento)
   {
      this.complemento = complemento;
   }

   public java.lang.String getBairro()
   {
      return this.bairro;
   }

   public void setBairro(java.lang.String bairro)
   {
      this.bairro = bairro;
   }

   public java.lang.String getLocalidade()
   {
      return this.localidade;
   }

   public void setLocalidade(java.lang.String localidade)
   {
      this.localidade = localidade;
   }

   public java.lang.String getUf()
   {
      return this.uf;
   }

   public void setUf(java.lang.String uf)
   {
      this.uf = uf;
   }

   public java.lang.String getUnidade()
   {
      return this.unidade;
   }

   public void setUnidade(java.lang.String unidade)
   {
      this.unidade = unidade;
   }

   public java.lang.String getIbge()
   {
      return this.ibge;
   }

   public void setIbge(java.lang.String ibge)
   {
      this.ibge = ibge;
   }

   public java.lang.String getGia()
   {
      return this.gia;
   }

   public void setGia(java.lang.String gia)
   {
      this.gia = gia;
   }

   public endereco(java.lang.String cep, java.lang.String logradouro,
         java.lang.String complemento, java.lang.String bairro,
         java.lang.String localidade, java.lang.String uf,
         java.lang.String unidade, java.lang.String ibge,
         java.lang.String gia)
   {
      this.cep = cep;
      this.logradouro = logradouro;
      this.complemento = complemento;
      this.bairro = bairro;
      this.localidade = localidade;
      this.uf = uf;
      this.unidade = unidade;
      this.ibge = ibge;
      this.gia = gia;
   }

}